name: Node CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
